# Numpy

- Orientado a arrays.
- No necesita tanto de loops como pandas.
- Los algoritmos son de 10 a 100 veces más rápidos y usan menos memoria.

Los arrays nos permiten realizar operaciones matemáticas de bloques de integers con similar sintaxis que escalares:

In [1]:
import numpy as np

In [2]:
data= np.random.randn(2,3)

print(data)

[[ 0.75923915 -0.18172046  0.10222359]
 [-1.0636909  -0.23112772  1.1301201 ]]


In [3]:
print(data * 10)

[[  7.5923915   -1.8172046    1.02223585]
 [-10.63690898  -2.31127717  11.30120098]]


In [4]:
print(data + data)

[[ 1.5184783  -0.36344092  0.20444717]
 [-2.1273818  -0.46225543  2.2602402 ]]


Un array debe contener datos homogéneos, es decir, todos los elementos deben ser del mismo tipo. Cada array tiene un shape, un tuple que indica el tamaño de cada dimensión (filas y columnas).

Cada array tiene un dtype, es decir, un objeto que describr el tipo de arrays:

In [6]:
data.shape

(2, 3)

In [7]:
data.dtype

dtype('float64')

## Crear Arrays

La mejor forma de crear arrays es usando la función "array". Ejemplo:

In [9]:
data1= [6, 7.5, 8, 0, 1]  #tupple

In [11]:
arr1= np.array(data1)

print(arr1)

arr1

[6.  7.5 8.  0.  1. ]


array([6. , 7.5, 8. , 0. , 1. ])

In [14]:
data2= [[1, 2, 3, 4], [5, 6, 7, 8]]

print(data2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [15]:
arr2= np.array(data2)

print(arr2)

arr2

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
print(arr2.dtype)

print(arr2.shape)

int32
(2, 4)


Podemos ver que nos indica que tiene 2 filas y 4 columnas. 

Podemos además, como en matlab, crear matrices de ceros y unos:

In [19]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

También podemos usar una función empty para crear arrays:

In [21]:
np.empty((2, 3, 2))

array([[[1.50669890e-312, 0.00000000e+000],
        [8.76794447e+252, 2.15895723e+227],
        [6.48224638e+170, 3.67145870e+228]],

       [[7.58253645e-096, 9.03292329e+271],
        [9.08366793e+223, 1.41075687e+232],
        [1.16070543e-028, 2.98505553e+296]]])

Se trata de 2 dimensiones, 3 filas y 2 columnas.

No pensar que empty devuelve ceros, como vemos, no son ceros.

Otro ejemplo:

In [22]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Tipos de datos para Arrays

Los arrays son un tipo de objeto especial.

In [6]:
arr1= np.array([1, 2, 3])

print(arr1.dtype)

int32


En página 91 se entuentran todos los tipos de datos.

Podemos pasar de un tipo de dato a otro:

In [10]:
arr= np.array([1, 2, 3, 4, 5])

print(arr.dtype)

print(arr)

int32
[1 2 3 4 5]


In [9]:
float_arr= arr.astype(np.float64)

print(float_arr.dtype)

print(float_arr)

float64
[1. 2. 3. 4. 5.]


Si aplicamos esto mismo al revés, la parte de decimales se trunca.

Para convertir de string a número:

In [12]:
numeric_strings= np.array(["1.25", "-9.6", "42"])

print(numeric_strings.dtype)

print(numeric_strings)

<U4
['1.25' '-9.6' '42']


Lo pasamos a float:

In [15]:
numeric_strings= numeric_strings.astype(float)

print(numeric_strings.dtype)

float64


Para manipular datos no numéricos siempre es mejor pandas. Si el float arroja error en la conversión, probar float64.

También podemos usar el atributo de otro array para la conversión:

In [16]:
int_array= np.arange(10)

print(int_array)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
calibers= np.array([.22, .270, .357], dtype= np.float64)

print(calibers)

print(calibers.dtype)

[0.22  0.27  0.357]
float64


In [18]:
int_array= int_array.astype(calibers.dtype)

print(int_array)

print(int_array.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


"astype" siempre crea un nuevo array.