# Operaciones Aritméticas

La ventaja de estas operaciones es que nos permiten llevar adelante estas operaciones sin necesidad de for loops.

In [2]:
import numpy as np

In [3]:
arr= np.array([[1., 2., 3.], [4., 5., 6.]])

print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


In [4]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [7]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [9]:
print((arr ** 5).astype(int))

[[   1   32  243]
 [1024 3125 7776]]


In [11]:
arr2= np.array([[0., 4., 1.], [7., 2., 12.]])

print(arr2)

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


In [12]:
print(arr2 == arr)

[[False False False]
 [False False False]]


In [13]:
print(arr2 > arr)

[[False  True False]
 [ True False  True]]


In [14]:
print(arr2 < arr)

[[ True False  True]
 [False  True False]]
