# Basic Indexing and Slicing

## Indexing

In [1]:
import numpy as np

In [3]:
arr= np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
arr1= arr[5]

print(arr1)

5


Es importante mencionar que en el entorno jupyter el array original no se modifica como si pasa en el entorno común de python.

In [12]:
arr2= arr[5:8]

print(arr2)

[5 6 7]


Si queremos reemplazar un valor en alguna sección del array (en este caso si se reemplaza el original):

In [14]:
arr[5:8]= 12

print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [15]:
arr3= np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(arr3[2])

[7 8 9]


In [20]:
print(arr3[2][2])

9


A la función anterior también la podemos reescribir como:

In [21]:
print(arr3[2,2])

9


En el caso de queres hacer una copia de un array, debemos proceder de la siguiente manera:

In [22]:
copia= arr.copy()

print(copia)

[ 0  1  2  3  4 12 12 12  8  9]


In [25]:
print(copia is arr)

False


In [ ]:
arr_copia= arr

print(arr_copia is arr)

Como vemos, "arr_copia" y "arr" son básicamente dos nombres distintos que apuntan al mismo objeto. Lo que hagamos con una, afecta también a la otra. Afectan al mismo objeto.

O, podemos copiar sólo una parte:

In [28]:
copia1= arr[2].copy()

print(copia1)

2


## Slicing

In [29]:
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(arr3[:2])

[[1 2 3]
 [4 5 6]]


In [41]:
print(arr3[:2][1:])

[[4 5 6]]


La manera para indicar slicing de filas y columnas es la siguiente:

In [43]:
print(arr3[:2, 1:])

[[2 3]
 [5 6]]


In [44]:
print(arr3[:,:1])

[[1]
 [4]
 [7]]


Recordar que al hacer slicing, no se incluye en el resultado la última fila/columna indicada.