# Fancy Indexing

In [2]:
import numpy as np

In [3]:
arr= np.empty((8,4))

print(arr)

[[2.22523004e-307 2.11392033e-307 1.60216183e-306 7.56602523e-307]
 [1.11258446e-306 4.45063578e-308 1.22383816e-307 1.33509389e-306]
 [6.23057349e-307 9.34609790e-307 6.95370382e-308 1.33511018e-306]
 [1.29061142e-306 4.45064003e-308 1.11260687e-306 2.11387449e-307]
 [1.37962185e-306 1.78020848e-306 3.56036603e-307 1.44635488e-307]
 [1.37962320e-306 1.29060871e-306 1.24611266e-306 2.78149851e-307]
 [1.24610994e-306 1.78020848e-306 4.00526876e-307 7.56577398e-307]
 [9.34600963e-307 1.78020848e-306 1.02360867e-306 4.45057637e-308]]


In [4]:
for i in range(8):
    arr[i]= i
    
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


Para seleccionar sublistas en un orden específico, hacemos lo siguiente:

In [5]:
arr1= arr[[4, 3, 0, 6]]

print(arr1)

[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


También se puede seleccionar con negativos, para contar de atrás para adelante. Al hacerlo, comienza a contar desde 1:

In [6]:
arr2= arr[[-3, -5, -7]]

print(arr2)

[[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]


In [7]:
arr3= np.arange(32).reshape((8,4))

print(arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [8]:
arr4= arr3[[1, 5, 7, 2],[0, 3, 1, 2]]

print(arr4)

[ 4 23 29 10]


El primer tuple sirve para identificar las filas, el segundo va identificando el integer de cada fila.