# Transponer

Transponer es una forma especial de reshape que devuelve otra lista de los elementos.

In [2]:
import numpy as np

In [3]:
arr= np.arange(15).reshape((3,5))

print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [4]:
arr1= arr.T

print(arr1)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


3 filas = 3 columnas

5 columnas = 5 filas