# Condicionales

In [1]:
import numpy as np

In [2]:
xarr= np.array([1.1, 1.2, 1.3, 1.4, 1.5])

yarr= np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond= np.array([True, False, True, True, False])

Queremos tomar el valor de xarr cuando el valor de cond es True, de lo contrario yarr. Sin duda esto podría hacerse con un loop, pero es mucho más rápido con la función np.where:

In [3]:
result= np.where(cond, xarr, yarr)

print(result)

[1.1 2.2 1.3 1.4 2.5]


El segundo y tercer elemento de la función, no necesitan ser arrays, pueden ser escalares.

Supongamos que queremos reemplazar todos los valores positivos de una matriz con 2 y todos los negativos con -2:

In [4]:
arr= np.random.randn(4,4)

print(arr)

[[-1.19300827 -0.02208577  0.25071348  0.56337384]
 [ 0.53792126  0.37930192  2.16776255 -0.32144565]
 [-0.32730869  0.18917925 -0.23374401  0.10806527]
 [-0.47945115  1.31670854  0.33171865 -1.52340704]]


In [5]:
arr1= np.where(arr > 0, 2, -2)

print(arr1)

[[-2 -2  2  2]
 [ 2  2  2 -2]
 [-2  2 -2  2]
 [-2  2  2 -2]]


También se pueden combinar escalares con arrays:

In [6]:
arr2= np.where(arr > 0, 2, arr)

print(arr2)

[[-1.19300827 -0.02208577  2.          2.        ]
 [ 2.          2.          2.         -0.32144565]
 [-0.32730869  2.         -0.23374401  2.        ]
 [-0.47945115  2.          2.         -1.52340704]]
