# Métodos Matemáticos y Estadísticos

In [1]:
import numpy as np

In [2]:
arr= np.random.randn(5,4)

print(arr)

[[-0.56432555 -0.35309267  0.09534657  0.65399967]
 [ 0.54891118 -0.56800301 -1.50829576  0.07209043]
 [ 0.12027721 -0.45149052 -0.61017436 -1.32162656]
 [-0.3032201   1.32801426  0.48327007  0.53190867]
 [ 0.80389287  0.78513353  0.94456254  1.17644007]]


Dos métodos para calcular el promedio:

In [5]:
mean1= arr.mean()

print(mean1)

0.09318092667818809


In [6]:
mean2= np.mean(arr)

print(mean2)

0.09318092667818809


Dos métodos para calcular la suma:

In [7]:
sum1= arr.sum()

print(sum1)

1.8636185335637616


In [8]:
sum2= np.sum(arr)

print(sum2)

1.8636185335637616


Funciones como mean o sum pueden tomar un argumento adicional, a los efectos de hacer que el cómputo sea sobre una determinada fila o columna:

- 0 es fila
- 1 es columna

In [9]:
sum3= arr.sum(axis= 0)

print(sum3)

[ 0.60553561  0.74056159 -0.59529094  1.11281227]


In [10]:
mean3= arr.mean(axis= 1)

print(mean3)

[-0.04201799 -0.36382429 -0.56575356  0.50999322  0.92750725]


Hay otros métodos como cumsum o cumprod que van acumulando el resultado:

In [11]:
arr1= np.array([0, 1, 2, 3, 4, 5, 6, 7])

print(arr1)

[0 1 2 3 4 5 6 7]


In [15]:
print(arr1.cumsum())

print(arr1[1:].cumprod())  #Hago una slicing, sino el cero me devuelve sólo ceros

[ 0  1  3  6 10 15 21 28]
[   1    2    6   24  120  720 5040]


En array multidimensionales como una matriz, cumsum devuelve una sola fila, salvo que señalemos un axis.

In [16]:
arr2= np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print(arr2.cumsum())

[ 0  1  3  6 10 15 21 28 36]


In [18]:
print(arr2.cumsum(axis=0))

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


En el último caso, como podemos ver, va sumando a través de las filas.