# Sorting

In [10]:
import numpy as np

In [24]:
arr= np.random.randn(6)

print(arr)

[ 1.1267363  -0.4788318   0.37236782  1.57733246 -0.52384247 -0.39351379]


In [25]:
arr.sort()

print(arr)

[-0.52384247 -0.4788318  -0.39351379  0.37236782  1.1267363   1.57733246]


In [15]:
arr1= np.sort(arr)

print(arr1)

[-1.4880417   0.84354531  1.04080111  1.49197136  1.87673989  1.98576569]


Es recomendable siempre usar la función de numpy. Nos permite generar un nuevo elemento, algo que la función porpia de python no hace.

Si se trata de un array multidimensional, podemos elegir la dimensión a través de la cual hacemos el ordenamiento:

In [27]:
arr2= np.random.randn(5,3)

print(arr2)

[[ 0.01493288  0.95844246 -0.03888395]
 [-0.82571697 -0.8588006   0.12135768]
 [ 2.85482726  1.26181995 -0.21933231]
 [-0.21357297 -0.45462061  0.09480475]
 [-0.9552135  -0.74373655  0.45565067]]


In [29]:
arr3= np.sort(arr2, axis= 1)

print(arr3)

[[-0.03888395  0.01493288  0.95844246]
 [-0.8588006  -0.82571697  0.12135768]
 [-0.21933231  1.26181995  2.85482726]
 [-0.45462061 -0.21357297  0.09480475]
 [-0.9552135  -0.74373655  0.45565067]]


In [30]:
arr2.sort(1)

print(arr2)

[[-0.03888395  0.01493288  0.95844246]
 [-0.8588006  -0.82571697  0.12135768]
 [-0.21933231  1.26181995  2.85482726]
 [-0.45462061 -0.21357297  0.09480475]
 [-0.9552135  -0.74373655  0.45565067]]
